title: Lucas Lima
description: Assistant Professor of Economics at PUC-Rio
locale: en_US
url: https://lucasaelima.github.io
baseurl: ""

owner:
  name: Lucas Lima
  avatar: homer.jpeg
  bio: "Assistant Professor<br>Department of Economics<br>PUC-Rio"
  email: lucas.lima@econ.puc-rio.br

permalink: /:categories/:title/
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
